version: '3'
services:
  api:
    image: node:latest
    working_dir: /code
    ports:
      - 3000:3000
    environment:
    - PGUSER=team_pino
    - PGPASSWORD=pinopino
    - PGHOST=db
    - PGDATABASE=library
    - PGPORT=5432
    depends_on:
     - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run test"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=team_pino
      - POSTGRES_PASSWORD=pinopino
volumes:
  dbdata:
